# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    env:
      LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install -g @lhci/cli@latest
      - run: lhci autorun

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v5

    - name: Testing Options
      id: validate
      uses: Cyb3r-Jak3/html5validator-action@v8.0.0
      continue-on-error: true
      with:
        root: .
        format: text
        log_level: INFO
        extra: -lll

    - uses: actions/upload-artifact@v4
      with:
        name: log
        path: log.log

    - name: Get information
      run: echo "${{ steps.validate.outputs.result }}"
